### ISSUE TITLE
sometime entry 'Error: write after end' when get big logfile as attachment

### ISSUE THREAD

**Issue by JunejaTung** [expressjs/compression#76]
## backgroud
the web-front request logfile with `get` method through http-server from ftp-server. Specifically http-server read logfile from ftp-server and response web-front with attachment.

## sometime entry error
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:428:15)
    at ServerResponse.res.write (/workspace/sysmonitor/node_modules/compression/index.js:87:17)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.source.emit (/workspace/sysmonitor/node_modules/ftp/lib/connection.js:568:20)
    at Socket.Readable.read (_stream_readable.js:360:10)
    at flow (_stream_readable.js:743:26)
    at ServerResponse.<anonymous> (_stream_readable.js:601:7)
    at emitNone (events.js:67:13)
    at ServerResponse.emit (events.js:166:7)
    at Socket.ondrain (_http_common.js:189:44)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at onwriteDrain (_stream_writable.js:356:12)
    at afterWrite (_stream_writable.js:344:5)
    at onwrite (_stream_writable.js:337:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)
```
## relative code
```js
    } else {
            readstream.once('close', function () {
              console.log('Readstream of ftp closed for file:' + ftppath);

              ftpins.end();
            });

            if(result.numBytes > status.tdLogSizeGate) {
              res.setHeader("Content-Disposition", "attachment;filename=" + logname);
              readstream.pipe(res);
            } else {
              res.setHeader("Content-Disposition", "inline;filename=" + logname);
              readstream.pipe(res);
            }
          }
```

**Comment by dougwilson** [comment]
Hi! According to your stack trace, your are just passing through without compression. This means that you would have the error regardless of if this module was even used in your server, and the error is coming from Node.js itself.

If you think this information is in error, please provde complete information in order for us to reproduce the issue. Required information is the following:

1. Version of Node.js you are using
2. Version of this module you are using
3. Complete code we can run that reproduces the issue
4. Complete instructions on how we can reproduce the issue

**Comment by dougwilson** [comment]
According to https://github.com/mscdex/node-ftp/issues/70 it seems like with the `ftp` module you are using, there are bugs when you `.pipe(res)`. Have you tried using the work-arounds suggested in that issue? Perhaps try a different ftp module?

The comment https://github.com/mscdex/node-ftp/issues/70#issuecomment-108289122 seems to say that the `ftp` module stream may be emitting end before it's finished writing, which would be the exact error you are seeing here.

**Comment by JunejaTung** [comment]
@dougwilson yes, i have the save doubt about ftp module i used. then i try to ensure res.end()  after the end event of ftp readstream, it runs ok!
